CREATE DATABASE nodejs_base1 CHARACTER SET utf8mb4;

USE nodejs_base1;

CREATE TABLE users(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(90) NOT NULL,
email VARCHAR(180) NOT NULL UNIQUE,
password VARCHAR(90) NOT NULL,
created_at TIMESTAMP(0) NOT NULL
);